import './globals.css'
import type { Metadata } from 'next'

// Importamos el navbar que creamos
import Nabvar from '@/components/Nabvar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="container mx-auto">
        {/* Colocamos la barra de navegación acá dentro */}
        <Nabvar/>
        {children}</body>
    </html>
  )
}
